Album para cada evento
juditecypreste/PyRoles pull request #17
Opened 2019-10-17 15:05 UTC by siqandressa

2019-10-17 15:06 UTC, siqandressa reviewed
Agora todas as fotos são salvas no unico album.. que é o album de referencia do ultimo evento.

2019-10-21 16:25 UTC, filipecifali requested changes

2019-10-21 16:25 UTC, filipecifali commented on .idea/PyRoles.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Esse arquivo é necessário para o PR?

2019-10-21 16:25 UTC, filipecifali commented on pyroles.conf.sample
> +[ALBUM]
Considerando que um dos desejos é ter também no Google Drive isso está perfeito 👍

2019-10-21 16:26 UTC, filipecifali commented
@siqandressa Obrigado pela contribuição, só fiquei com uma dúvida quanto a um arquivo enviado junto mas para mim já está aprovado.

2019-10-21 17:33 UTC, siqandressa commented
Qual seria a duvida?

Att
Andressa Siqueira

Eng. Eletricista com ênfase em Sistema e Computação
Mestre em Sistema e Computação

"Pensamentos tornam-se ações, ações tornam-se hábitos, hábitos tornam-se
caráter, e nosso caráter torna-se nosso destino” (autor desconhecido)

Linkedin: http://www.linkedin.com/in/andressasiqueira


On Mon, Oct 21, 2019 at 1:26 PM Filipe Cifali Stangler <
notifications@github.com> wrote:

> @siqandressa <https://github.com/siqandressa> Obrigado pela contribuição,
> só fiquei com uma dúvida quanto a um arquivo enviado junto mas para mim já
> está aprovado.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pythonbrasil/PyRoles/pull/17?email_source=notifications&email_token=AB7IVEKDE4NM64Q7KFODIKDQPXJ2DA5CNFSM4JB3BG22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB25YIY#issuecomment-544594979>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB7IVEJUTW456G3IOTDLYHTQPXJ2DANCNFSM4JB3BG2Q>
> .
>

2019-10-21 17:34 UTC, siqandressa commented on .idea/PyRoles.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Não... devo ter selecionado por engano.

2019-10-21 17:34 UTC, siqandressa commented on pyroles.conf.sample
> +[ALBUM]
obrigada

2019-10-21 18:43 UTC, filipecifali commented
@siqandressa vi aqui que você fez o commit depois, era isso mesmo obrigado!

2019-10-21 18:45 UTC, siqandressa commented
de nada!

Andressa Siqueira

Eng. Eletricista com ênfase em Sistema e Computação
Mestre em Sistema e Computação

"Pensamentos tornam-se ações, ações tornam-se hábitos, hábitos tornam-se
caráter, e nosso caráter torna-se nosso destino” (autor desconhecido)

Linkedin: http://www.linkedin.com/in/andressasiqueira


On Mon, Oct 21, 2019 at 3:43 PM Filipe Cifali Stangler <
notifications@github.com> wrote:

> @siqandressa <https://github.com/siqandressa> vi aqui que você fez o
> commit depois, era isso mesmo obrigado!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pythonbrasil/PyRoles/pull/17?email_source=notifications&email_token=AB7IVEJVPZ2YCISSD4M2YUDQPXZ6JA5CNFSM4JB3BG22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB3LVEQ#issuecomment-544651922>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB7IVEM4FRY3WIOJXA5EF6DQPXZ6JANCNFSM4JB3BG2Q>
> .
>

2019-10-21 18:51 UTC, dunossauro commented on PyRoles.py
> +    bot.reply_to(message,message_return , parse_mode="HTML", disable_web_page_preview=True)
Pensar em padronizar essa parte de acordo com as normas da PEP-8.

Na realidade osproblemas estão nos espaços.

Na lista 36: Deve ser adicionado o espaço

`message_return = u`

Na linha 37: deve ser removido o espaço

`message,message_return, `

2020-02-03 13:52 UTC, merged